name: Autotest

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Pipenv
      run: python -m pip install pipenv
    - name: Bootstrap
      run: pipenv install --dev
    # - name: Test
    #   run: pipenv run pytest --capture=no --verbosity=2 --cov=application --cov-report=term-missing
